//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetRDV247.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class rendezvous
    {
        public int id_rdv { get; set; }
        public System.DateTime debut_rdv { get; set; }
        public System.DateTime fin_rdv { get; set; }
        public string statut_rdv { get; set; }
        public Nullable<int> id_client_rdv { get; set; }
        public int id_employe_rdv { get; set; }
        public int id_typerdv_rdv { get; set; }
    
        public virtual client client { get; set; }
        public virtual employe employe { get; set; }
        public virtual typerdv typerdv { get; set; }
    }
}
